#!/usr/bin/env bash
# Create necessary folders for BGP lab environment

# Get the current working directory
CURRENT_DIR="$(pwd)"
BGP_LAB_DIR="$CURRENT_DIR/docker-bgp"

echo "Creating BGP lab directory structure at: $BGP_LAB_DIR"

# Create main directory
mkdir -p "$BGP_LAB_DIR"

# Create docker-compose.yml
cat > "$BGP_LAB_DIR/docker-compose.yml" << 'EOF'
version: '3.8'
services:
  # Add your BGP lab services here
  # Example structure for FRRouting containers
EOF

# Create client directory with Dockerfile
mkdir -p "$BGP_LAB_DIR/client"
cat > "$BGP_LAB_DIR/client/Dockerfile" << 'EOF'
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y \
    iputils-ping \
    traceroute \
    curl \
    tcpdump \
    net-tools
CMD ["/bin/bash"]
EOF

# List of AS directories to create
as_dirs=("as1000" "as2000" "as3000" "as1337")

# Loop through each AS directory and create it
for as_dir in "${as_dirs[@]}"; do
    echo "Creating directory: $as_dir"
    mkdir -p "$BGP_LAB_DIR/$as_dir"
    
    # Create frr.conf for each AS
    cat > "$BGP_LAB_DIR/$as_dir/frr.conf" << EOF
! FRRouting configuration for $as_dir
hostname $as_dir
!
! BGP configuration will be added here
!
EOF
    
    # Create daemons file for each AS
    cat > "$BGP_LAB_DIR/$as_dir/daemons" << EOF
# This file tells the frr package which daemons to start.
#
# Sample configurations for these daemons can be found in
# /usr/share/doc/frr/examples/.
#
# ATTENTION:
#
# When activating a daemon for the first time, a config file, even if it is
# empty, has to be present *and* be owned by the user and group "frr", else
# the daemon will not be started by /etc/init.d/frr. The permissions should
# be u=rw,g=r,o=.
# When using "vtysh" such a config file is also needed. It should be owned by
# group "frrvty" and set to ug=rw,o= though. Check /etc/pam.d/frr, too.
#
# The watchfrr and zebra daemons are always started.
#
zebra=yes
bgpd=yes
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no

#
# If this option is set the /etc/init.d/frr script automatically loads
# the config via "vtysh -b" when the servers are started.
# Check /etc/pam.d/frr if you intend to use "vtysh"!
#
vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
bgpd_options="   -A 127.0.0.1"
ospfd_options="  -A 127.0.0.1"
ospf6d_options=" -A ::1"
ripd_options="   -A 127.0.0.1"
ripngd_options=" -A ::1"
isisd_options="  -A 127.0.0.1"
pimd_options="   -A 127.0.0.1"
ldpd_options="   -A 127.0.0.1"
nhrpd_options="  -A 127.0.0.1"
eigrpd_options=" -A 127.0.0.1"
babeld_options=" -A 127.0.0.1"
sharpd_options=" -A 127.0.0.1"
pbrd_options="   -A 127.0.0.1"
staticd_options="-A 127.0.0.1"
bfdd_options="   -A 127.0.0.1"
fabricd_options="-A 127.0.0.1"

# The list of daemons to watch is automatically generated by the init script.
#watchfrr_options=""

# for debugging purposes, you can specify a "wrap" command to start instead
# of starting the daemon directly, e.g. to use valgrind on ospfd:
#   ospfd_wrap="/usr/bin/valgrind"
# or you can use "all_wrap" for all daemons, e.g. to use perf record:
#   all_wrap="/usr/bin/perf record --call-graph -"
# the normal daemon command is added to this at the end.
EOF
    
    # Create vtysh.conf for each AS
    cat > "$BGP_LAB_DIR/$as_dir/vtysh.conf" << EOF
! vtysh configuration file for $as_dir
!
! Add your vtysh configuration here
!
EOF
done

# Create special structure for as1000 (with Dockerfile and frr_patches)
echo "Creating special structure for as1000"
mkdir -p "$BGP_LAB_DIR/as1000/frr_patches"

cat > "$BGP_LAB_DIR/as1000/Dockerfile" << 'EOF'
FROM frrouting/frr:latest
COPY frr.conf /etc/frr/frr.conf
COPY frr_patches/ /etc/frr/patches/
RUN chown frr:frr /etc/frr/frr.conf
CMD ["/usr/lib/frr/docker-start"]
EOF

# Create a sample patch file
cat > "$BGP_LAB_DIR/as1000/frr_patches/sample.patch" << 'EOF'
# Sample FRR patch file
# Add your BGP patches here
EOF

echo "BGP lab directory structure created successfully!"
echo "Directory structure:"
tree "$BGP_LAB_DIR" 2>/dev/null || find "$BGP_LAB_DIR" -type d | sort 

